name: Lint and Fix Code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Prettier and ESLint
        run: |
          npm install --global prettier eslint

      - name: Run Prettier
        run: prettier --write "**/*.{js,css,html,md}"

      - name: Run ESLint
        run: eslint "**/*.js" --fix

  lint:
    runs-on: ubuntu-latest
    needs: fix
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter with detailed output
        uses: super-linter/super-linter/slim@latest
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISPLAY_ERRORS: true
