name: Lint and Fix Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@latest
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_JAVASCRIPT: true
          VALIDATE_ALL_CODEBASE: false
          LINTER_RULES_PATH: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  fix:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write "**/*.{js,css,html,md}"

      - name: Run ESLint
        run: npx eslint "**/*.js" --fix
